import React, { createContext, useState, useContext } from 'react';

const translations = {
  English: {
    navGroup_Navigation: 'Navigation',
    navGroup_ClinicalCare: 'Clinical Care',
    navGroup_Diagnostics: 'Diagnostics & Pharmacy',
    navGroup_PatientFlow: 'Patient Flow & Billing',

    mod_home: 'Home',
    mod_dashboard: 'Dashboard',
    mod_outpatient: 'Outpatient Mgmt',
    mod_inpatient: 'Inpatient Mgmt',
    mod_nursing: 'Nursing (NIS)',
    mod_clinical_pharm: 'Clinical Pharmacy',
    mod_tumor_board: 'Tumor Board',
    mod_quality: 'Clinical Quality',
    mod_lis: 'Laboratory Info System (LIS)',
    mod_ris: 'Radiology Info System (RIS)',
    mod_pharmacy: 'Pharmacy Management',
    mod_patient_billing: 'Patient Billing',
    mod_revenue_cycle: 'Revenue Cycle',

    desc_outpatient: 'Streamline Ambulatory Care',
    desc_inpatient: 'Coordinate Holistic Inpatient Care',
    desc_nursing: 'Empower Connected Nursing Care',
    desc_clinical_pharm: 'Enhance Medication Safety',
    desc_tumor_board: 'Collaborative Cancer Care Decisions',
    desc_quality: 'Drive Quality Healthcare Outcomes',
    desc_lis: 'Accelerate Diagnostic Accuracy',
    desc_ris: 'Intelligent Imaging Operations',
    desc_pharmacy: 'Smarter Medication Management',
    desc_patient_billing: 'Simplify Financial Operations',
    desc_revenue_cycle: 'Maximize Revenue Performance',

    ui_hms: 'Hospital Management System',
    ui_lang: 'Choose Language',
    ui_profile: 'User Profile',
    ui_logout: 'Log Out',
    ui_dept: 'Oncology Dept.',
    ui_module_active: 'Module Active',
    ui_interface_dev: 'Interface In Development',
    ui_interface_desc: 'This module is part of the core VistaOnco architecture. The specific user interface components are currently being configured.',
    inpatient_admit: 'Admit Patient',
    inpatient_room: 'Room Number',
    inpatient_bed: 'Bed Number',
    inpatient_date: 'Admission Date',
    inpatient_status: 'Status',
    inpatient_discharge: 'Discharge Patient',
    inpatient_active: 'Active Admissions',
    inpatient_history: 'Admission History',
    inpatient_no_records: 'No active admissions found.',
    inpatient_discharge_date: 'Discharge Date',
    inpatient_select_patient: 'Select Patient',
    btn_cancel: 'Cancel',
    btn_save: 'Save',
    nursing_assessment: 'Patient Assessment',
    nursing_assessment_desc: 'Structured nursing assessments',
    nursing_med_admin: 'Medication Admin',
    nursing_med_admin_desc: 'Safe medication administration records',
    nursing_care_plans: 'Care Plans',
    nursing_care_plans_desc: 'Nursing care plan management',
    nursing_handover: 'Handover Notes',
    nursing_handover_desc: 'Digital shift handover documentation',
    pharmacy_new_order: 'New Order',
    pharmacy_medication: 'Medication Name',
    pharmacy_dosage: 'Dosage',
    pharmacy_frequency: 'Frequency',
    pharmacy_active: 'Active Orders Queue',
    pharmacy_history: 'Dispensed Orders History',
    pharmacy_verify: 'Verify Order',
    pharmacy_dispense: 'Dispense',
    pharmacy_status_pending: 'Pending',
    pharmacy_status_verified: 'Verified',
    pharmacy_status_dispensed: 'Dispensed',
    billing_new_invoice: 'New Invoice',
    billing_amount: 'Amount (₹)',
    billing_description: 'Description',
    billing_unpaid: 'Unpaid Invoices',
    billing_paid: 'Paid Invoices History',
    billing_mark_paid: 'Mark as Paid',
    billing_status_unpaid: 'Unpaid',
    billing_status_paid: 'Paid',
    billing_total_unpaid: 'Total Unpaid',
    billing_total_revenue: 'Total Revenue',
    tb_meetings: 'Meetings',
    tb_new_meeting: 'Schedule Meeting',
    tb_date: 'Meeting Date',
    tb_location: 'Location',
    tb_cases: 'Patient Cases',
    tb_add_case: 'Present Patient Case',
    tb_summary: 'Clinical Summary',
    tb_decision: 'Board Decision',
    tb_record_decision: 'Record Decision',
    tb_save_decision: 'Save',
    qual_active_incidents: 'Active Incidents',
    qual_resolved_incidents: 'Resolved Incidents History',
    qual_report_incident: 'Report Incident',
    qual_date: 'Date',
    qual_department: 'Department',
    qual_severity: 'Severity',
    qual_description: 'Description',
    qual_status: 'Status',
    qual_resolve: 'Resolve',
    qual_sev_low: 'Low',
    qual_sev_medium: 'Medium',
    qual_sev_high: 'High',
    qual_sev_critical: 'Critical',
    qual_stat_open: 'Open',
    qual_stat_investigating: 'Investigating',
    qual_stat_resolved: 'Resolved',
    lis_active_labs: 'Active Lab Orders',
    lis_completed_labs: 'Completed Tests',
    lis_new_order: 'New Lab Order',
    lis_test_name: 'Test Name',
    lis_ordered_by: 'Ordered By',
    lis_status: 'Status',
    lis_notes: 'Notes',
    lis_stat_ordered: 'Ordered',
    lis_stat_collected: 'Collected',
    lis_stat_processing: 'Processing',
    lis_stat_resulted: 'Resulted',
    lis_action_collect: 'Mark Collected',
    lis_action_process: 'Start Processing',
    lis_action_result: 'Enter Results',
  },
  Hindi: {
    navGroup_Navigation: 'नेविगेशन',
    navGroup_ClinicalCare: 'क्लिनिकल केयर',
    navGroup_Diagnostics: 'निदान और फार्मेसी',
    navGroup_PatientFlow: 'रोगी प्रवाह और बिलिंग',

    mod_home: 'होम',
    mod_dashboard: 'डैशबोर्ड',
    mod_outpatient: 'बाह्य रोगी प्रबंधन',
    mod_inpatient: 'भर्ती रोगी प्रबंधन',
    mod_nursing: 'नर्सिंग (NIS)',
    mod_clinical_pharm: 'क्लिनिकल फार्मेसी',
    mod_tumor_board: 'ट्यूमर बोर्ड',
    mod_quality: 'क्लिनिकल गुणवत्ता',
    mod_lis: 'प्रयोगशाला सूचना प्रणाली (LIS)',
    mod_ris: 'रेडियोलॉजी सूचना प्रणाली (RIS)',
    mod_pharmacy: 'फार्मेसी प्रबंधन',
    mod_patient_billing: 'रोगी बिलिंग',
    mod_revenue_cycle: 'राजस्व चक्र',

    desc_outpatient: 'एंबुलेटरी देखभाल को कारगर बनाना',
    desc_inpatient: 'समग्र इनपेशेंट देखभाल का समन्वय',
    desc_nursing: 'कनेक्टेड नर्सिंग केयर को सशक्त बनाना',
    desc_clinical_pharm: 'दवा सुरक्षा बढ़ाएँ',
    desc_tumor_board: 'सहयोगात्मक कैंसर देखभाल निर्णय',
    desc_quality: 'गुणवत्तापूर्ण स्वास्थ्य सेवा परिणाम',
    desc_lis: 'नैदानिक सटीकता में तेजी लाना',
    desc_ris: 'बुद्धिमान इमेजिंग संचालन',
    desc_pharmacy: 'स्मार्ट दवा प्रबंधन',
    desc_patient_billing: 'वित्तीय संचालन को सरल बनाना',
    desc_revenue_cycle: 'राजस्व प्रदर्शन को अधिकतम करना',

    ui_hms: 'अस्पताल प्रबंधन प्रणाली',
    ui_lang: 'भाषा चुनें',
    ui_profile: 'उपयोगकर्ता प्रोफ़ाइल',
    ui_logout: 'लॉग आउट',
    ui_dept: 'ऑन्कोलॉजी विभाग',
    ui_module_active: 'मॉड्यूल सक्रिय',
    ui_interface_dev: 'इंटरफ़ेस विकास में है',
    ui_interface_desc: 'यह मॉड्यूल मुख्य विस्टाऑन्को आर्किटेक्चर का हिस्सा है। विशिष्ट यूजर इंटरफेस घटक वर्तमान में कॉन्फ़िगर किए जा रहे हैं।',
    inpatient_admit: 'रोगी भर्ती करें',
    inpatient_room: 'कमरा नंबर',
    inpatient_bed: 'बिस्तर नंबर',
    inpatient_date: 'भर्ती की तिथि',
    inpatient_status: 'स्थिति',
    inpatient_discharge: 'रोगी को डिस्चार्ज करें',
    inpatient_active: 'सक्रिय भर्तियां',
    inpatient_history: 'भर्ती इतिहास',
    inpatient_no_records: 'कोई सक्रिय भर्ती नहीं मिली।',
    inpatient_discharge_date: 'डिस्चार्ज तिथि',
    inpatient_select_patient: 'रोगी चुनें',
    btn_cancel: 'रद्द करें',
    btn_save: 'सहेजें',
    nursing_assessment: 'रोगी मूल्यांकन',
    nursing_assessment_desc: 'संरचित नर्सिंग मूल्यांकन',
    nursing_med_admin: 'दवा प्रशासन',
    nursing_med_admin_desc: 'सुरक्षित दवा प्रशासन रिकॉर्ड',
    nursing_care_plans: 'देखभाल योजनाएं',
    nursing_care_plans_desc: 'नर्सिंग देखभाल योजना प्रबंधन',
    nursing_handover: 'हैंडओवर नोट्स',
    nursing_handover_desc: 'डिजिटल शिफ्ट हैंडओवर दस्तावेज़ीकरण',
    pharmacy_new_order: 'नया आदेश',
    pharmacy_medication: 'दवा का नाम',
    pharmacy_dosage: 'खुराक',
    pharmacy_frequency: 'आवृत्ति',
    pharmacy_active: 'सक्रिय आदेश कतार',
    pharmacy_history: 'वितरित आदेश इतिहास',
    pharmacy_verify: 'आदेश सत्यापित करें',
    pharmacy_dispense: 'वितरित करें',
    pharmacy_status_pending: 'लंबित',
    pharmacy_status_verified: 'सत्यापित',
    pharmacy_status_dispensed: 'वितरित',
    billing_new_invoice: 'नया चालान',
    billing_amount: 'राशि (₹)',
    billing_description: 'विवरण',
    billing_unpaid: 'अवैतनिक चालान',
    billing_paid: 'भुगतान किए गए चालान इतिहास',
    billing_mark_paid: 'भुगतान के रूप में चिह्नित करें',
    billing_status_unpaid: 'अवैतनिक',
    billing_status_paid: 'भुगतान किया गया',
    billing_total_unpaid: 'कुल अवैतनिक',
    billing_total_revenue: 'कुल राजस्व',
    tb_meetings: 'बैठकें',
    tb_new_meeting: 'बैठक अनुसूची',
    tb_date: 'बैठक की तिथि',
    tb_location: 'स्थान',
    tb_cases: 'रोगी के मामले',
    tb_add_case: 'रोगी का मामला प्रस्तुत करें',
    tb_summary: 'नैदानिक सारांश',
    tb_decision: 'बोर्ड का निर्णय',
    tb_record_decision: 'निर्णय दर्ज करें',
    tb_save_decision: 'सहेजें',
    qual_active_incidents: 'सक्रिय घटनाएँ',
    qual_resolved_incidents: 'सुलझाई गई घटनाओं का इतिहास',
    qual_report_incident: 'घटना की रिपोर्ट करें',
    qual_date: 'दिनांक',
    qual_department: 'विभाग',
    qual_severity: 'गंभीरता',
    qual_description: 'विवरण',
    qual_status: 'स्थिति',
    qual_resolve: 'समाधान करें',
    qual_sev_low: 'कम',
    qual_sev_medium: 'मध्यम',
    qual_sev_high: 'उच्च',
    qual_sev_critical: 'अत्यंत गंभीर',
    qual_stat_open: 'खुला है',
    qual_stat_investigating: 'जांच जारी',
    qual_stat_resolved: 'हल किया गया',
    lis_active_labs: 'सक्रिय लैब आदेश',
    lis_completed_labs: 'पूरे किए गए परीक्षण',
    lis_new_order: 'नया लैब आदेश',
    lis_test_name: 'परीक्षण का नाम',
    lis_ordered_by: 'द्वारा आदेशित',
    lis_status: 'स्थिति',
    lis_notes: 'टिप्पणियाँ',
    lis_stat_ordered: 'आदेशित',
    lis_stat_collected: 'एकत्रित',
    lis_stat_processing: 'प्रसंस्करण',
    lis_stat_resulted: 'परिणामित',
    lis_action_collect: 'एकत्रित चिह्नित करें',
    lis_action_process: 'प्रसंस्करण शुरू करें',
    lis_action_result: 'परिणाम दर्ज करें',
  },
  Odia: {
    navGroup_Navigation: 'ନେଭିଗେସନ୍',
    navGroup_ClinicalCare: 'କ୍ଲିନିକାଲ୍ ଯତ୍ନ',
    navGroup_Diagnostics: 'ଡାଇଗ୍ନୋଷ୍ଟିକ୍ସ ଏବଂ ଫାର୍ମାସୀ',
    navGroup_PatientFlow: 'ରୋଗୀ ପ୍ରବାହ ଏବଂ ବିଲିଂ',

    mod_home: 'ହୋମ୍',
    mod_dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    mod_outpatient: 'ବାହ୍ୟ ରୋଗୀ ପରିଚାଳନା',
    mod_inpatient: 'ଆଭ୍ୟନ୍ତରୀଣ ରୋଗୀ ପରିଚାଳନା',
    mod_nursing: 'ନର୍ସିଂ (NIS)',
    mod_clinical_pharm: 'କ୍ଲିନିକାଲ୍ ଫାର୍ମାସୀ',
    mod_tumor_board: 'ଟ୍ୟୁମର୍ ବୋର୍ଡ',
    mod_quality: 'କ୍ଲିନିକାଲ୍ ଗୁଣବତ୍ତା',
    mod_lis: 'ପରୀକ୍ଷାଗାର ସୂଚନା ପ୍ରଣାଳୀ (LIS)',
    mod_ris: 'ରେଡିଓଲୋଜି ସୂଚନା ପ୍ରଣାଳୀ (RIS)',
    mod_pharmacy: 'ଫାର୍ମାସୀ ପରିଚାଳନା',
    mod_patient_billing: 'ରୋଗୀ ବିଲିଂ',
    mod_revenue_cycle: 'ରାଜସ୍ୱ ଚକ୍ର',

    desc_outpatient: 'ଆମ୍ବୁଲେଟାରୀ ଯତ୍ନକୁ ସରଳ କରିବା',
    desc_inpatient: 'ସାମଗ୍ରିକ ଇନପେସେଣ୍ଟ ଯତ୍ନର ସମନ୍ୱୟ',
    desc_nursing: 'ସଂଯୁକ୍ତ ନର୍ସିଂ ଯତ୍ନକୁ ସଶକ୍ତ କରିବା',
    desc_clinical_pharm: 'ଔଷଧ ସୁରକ୍ଷା ବଢାନ୍ତୁ',
    desc_tumor_board: 'ମିଳିତ କର୍କଟ ଯତ୍ନ ନିଷ୍ପତ୍ତି',
    desc_quality: 'ଗୁଣାତ୍ମକ ସ୍ୱାସ୍ଥ୍ୟ ସେବା ଫଳାଫଳ',
    desc_lis: 'ନିଦାନ ସଠିକତାକୁ ତ୍ୱରାନ୍ୱିତ କରିବା',
    desc_ris: 'ବୁଦ୍ଧିମାନ ଇମେଜିଙ୍ଗ୍ କାର୍ଯ୍ୟ',
    desc_pharmacy: 'ସ୍ମାର୍ଟ ଔଷଧ ପରିଚାଳନା',
    desc_patient_billing: 'ଆର୍ଥିକ କାର୍ଯ୍ୟକୁ ସରଳ କରିବା',
    desc_revenue_cycle: 'ରାଜସ୍ୱ ପ୍ରଦର୍ଶନକୁ ସର୍ବାଧିକ କରିବା',

    ui_hms: 'ଡାକ୍ତରଖାନା ପରିଚାଳନା ପ୍ରଣାଳୀ',
    ui_lang: 'ଭାଷା ବାଛନ୍ତୁ',
    ui_profile: 'ଉପଯୋଗକର୍ତ୍ତା ପ୍ରୋଫାଇଲ୍',
    ui_logout: 'ଲଗ୍ ଆଉଟ୍',
    ui_dept: 'ଅଙ୍କୋଲୋଜି ବିଭାଗ',
    ui_module_active: 'ମଡ୍ୟୁଲ୍ ସକ୍ରିୟ',
    ui_interface_dev: 'ଇଣ୍ଟରଫେସ୍ ବିକାଶ ଚାଲିଛି',
    ui_interface_desc: 'ଏହି ମଡ୍ୟୁଲ୍ ମୁଖ୍ୟ ଭିଷ୍ଟାଅଙ୍କୋ ଆର୍କିଟେକ୍ଚରର ଏକ ଅଂଶ। ନିର୍ଦ୍ଦିଷ୍ଟ ୟୁଜର ଇଣ୍ଟରଫେସ୍ ଉପାଦାନଗୁଡିକ ବର୍ତ୍ତମାନ କନଫିଗର କରାଯାଉଛି।',
    inpatient_admit: 'ରୋଗୀଙ୍କୁ ଭର୍ତ୍ତି କରନ୍ତୁ',
    inpatient_room: 'କକ୍ଷ ନମ୍ବର',
    inpatient_bed: 'ବେଡ୍ ନମ୍ବର',
    inpatient_date: 'ଭର୍ତ୍ତି ତାରିଖ',
    inpatient_status: 'ସ୍ଥିତି',
    inpatient_discharge: 'ରୋଗୀଙ୍କୁ ଡିସଚାର୍ଜ କରନ୍ତୁ',
    inpatient_active: 'ସକ୍ରିୟ ଭର୍ତ୍ତି',
    inpatient_history: 'ଭର୍ତ୍ତି ଇତିହାସ',
    inpatient_no_records: 'କୌଣସି ସକ୍ରିୟ ଭର୍ତ୍ତି ମିଳିଲା ନାହିଁ।',
    inpatient_discharge_date: 'ଡିସଚାର୍ଜ ତାରିଖ',
    inpatient_select_patient: 'ରୋଗୀ ବାଛନ୍ତୁ',
    btn_cancel: 'ବାତିଲ କରନ୍ତୁ',
    btn_save: 'ସେଭ୍ କରନ୍ତୁ',
    nursing_assessment: 'ରୋଗୀ ମୂଲ୍ୟାଙ୍କନ',
    nursing_assessment_desc: 'ସଂରଚିତ ନର୍ସିଂ ମୂଲ୍ୟାଙ୍କନ',
    nursing_med_admin: 'ଔଷଧ ପ୍ରଶାସନ',
    nursing_med_admin_desc: 'ସୁରକ୍ଷିତ ଔଷଧ ପ୍ରଶାସନ ରେକର୍ଡ',
    nursing_care_plans: 'ଯତ୍ନ ଯୋଜନା',
    nursing_care_plans_desc: 'ନର୍ସିଂ ଯତ୍ନ ଯୋଜନା ପରିଚାଳନା',
    nursing_handover: 'ହ୍ୟାଣ୍ଡଓଭର ନୋଟ୍',
    nursing_handover_desc: 'ଡିଜିଟାଲ୍ ସିଫ୍ଟ ହ୍ୟାଣ୍ଡଓଭର ଡକ୍ୟୁମେଣ୍ଟେସନ୍',
    pharmacy_new_order: 'ନୂତନ ଅର୍ଡର',
    pharmacy_medication: 'ଔଷଧର ନାମ',
    pharmacy_dosage: 'ଡୋଜ୍',
    pharmacy_frequency: 'ଫ୍ରିକ୍ୱେନ୍ସି',
    pharmacy_active: 'ସକ୍ରିୟ ଅର୍ଡର ଧାଡ଼ି',
    pharmacy_history: 'ବଣ୍ଟନ କରାଯାଇଥିବା ଅର୍ଡର ଇତିହାସ',
    pharmacy_verify: 'ଅର୍ଡର ଯାଞ୍ଚ କରନ୍ତୁ',
    pharmacy_dispense: 'ବଣ୍ଟନ କରନ୍ତୁ',
    pharmacy_status_pending: 'ପେଣ୍ଡିଂ',
    pharmacy_status_verified: 'ଯାଞ୍ଚ ହୋଇଛି',
    pharmacy_status_dispensed: 'ବଣ୍ଟନ କରାଯାଇଛି',
    billing_new_invoice: 'ନୂତନ ଇନଭଏସ୍',
    billing_amount: 'ପରିମାଣ (₹)',
    billing_description: 'ବିବରଣୀ',
    billing_unpaid: 'ପୈଠ ହୋଇନଥିବା ଇନଭଏସ୍',
    billing_paid: 'ପୈଠ ହୋଇଥିବା ଇନଭଏସ୍ ଇତିହାସ',
    billing_mark_paid: 'ପୈଠ ହୋଇଛି ବୋଲି ଚିହ୍ନିତ କରନ୍ତୁ',
    billing_status_unpaid: 'ପୈଠ ହୋଇନାହିଁ',
    billing_status_paid: 'ପୈଠ ହୋଇଛି',
    billing_total_unpaid: 'ମୋଟ ବାକି',
    billing_total_revenue: 'ମୋଟ ରାଜସ୍ୱ',
    tb_meetings: 'ମିଟିଂଗୁଡ଼ିକ',
    tb_new_meeting: 'ମିଟିଂ ନିର୍ଦ୍ଧାରଣ କରନ୍ତୁ',
    tb_date: 'ମିଟିଂ ତାରିଖ',
    tb_location: 'ସ୍ଥାନ',
    tb_cases: 'ରୋଗୀଙ୍କ ମାମଲା',
    tb_add_case: 'ରୋଗୀଙ୍କ ମାମଲା ଉପସ୍ଥାପନ କରନ୍ତୁ',
    tb_summary: 'କ୍ଲିନିକାଲ୍ ବିବରଣୀ',
    tb_decision: 'ବୋର୍ଡ ନିଷ୍ପତ୍ତି',
    tb_record_decision: 'ନିଷ୍ପତ୍ତି ରେକର୍ଡ କରନ୍ତୁ',
    tb_save_decision: 'ସେଭ୍ କରନ୍ତୁ',
    qual_active_incidents: 'ସକ୍ରିୟ ଘଟଣାଗୁଡ଼ିକ',
    qual_resolved_incidents: 'ସମାଧାନ ହୋଇଥିବା ଘଟଣା ଇତିହାସ',
    qual_report_incident: 'ଘଟଣା ରିପୋର୍ଟ କରନ୍ତୁ',
    qual_date: 'ତାରିଖ',
    qual_department: 'ବିଭାଗ',
    qual_severity: 'ଗୁରୁତ୍ୱ',
    qual_description: 'ବିବରଣୀ',
    qual_status: 'ସ୍ଥିତି',
    qual_resolve: 'ସମାଧାନ କରନ୍ତୁ',
    qual_sev_low: 'କମ୍',
    qual_sev_medium: 'ମଧ୍ୟମ',
    qual_sev_high: 'ଉଚ୍ଚ',
    qual_sev_critical: 'ଅତି ଗୁରୁତର',
    qual_stat_open: 'ଖୋଲା ଅଛି',
    qual_stat_investigating: 'ଅନୁସନ୍ଧାନ ଚାଲିଛି',
    qual_stat_resolved: 'ସମାଧାନ ହୋଇଛି',
    lis_active_labs: 'ସକ୍ରିୟ ଲ୍ୟାବ୍ ଅର୍ଡରଗୁଡ଼ିକ',
    lis_completed_labs: 'ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଥିବା ପରୀକ୍ଷାଗୁଡ଼ିକ',
    lis_new_order: 'ନୂତନ ଲ୍ୟାବ୍ ଅର୍ଡର',
    lis_test_name: 'ପରୀକ୍ଷା ନାମ',
    lis_ordered_by: 'ଦ୍ୱାରା ଅର୍ଡର କରାଯାଇଛି',
    lis_status: 'ସ୍ଥିତି',
    lis_notes: 'ଟିପ୍ପଣୀଗୁଡ଼ିକ',
    lis_stat_ordered: 'ଅର୍ଡର କରାଯାଇଛି',
    lis_stat_collected: 'ସଂଗ୍ରହ କରାଯାଇଛି',
    lis_stat_processing: 'ପ୍ରକ୍ରିୟାକରଣ ଚାଲିଛି',
    lis_stat_resulted: 'ଫଳାଫଳ ବାହାରିଛି',
    lis_action_collect: 'ସଂଗ୍ରହ କରାଯାଇଛି ବୋଲି ଚିହ୍ନିତ କରନ୍ତୁ',
    lis_action_process: 'ପ୍ରକ୍ରିୟାକରଣ ଆରମ୍ଭ କରନ୍ତୁ',
    lis_action_result: 'ଫଳାଫଳ ପ୍ରବେଶ କରନ୍ତୁ',
  },
  Marathi: {
    navGroup_Navigation: 'नेव्हिगेशन',
    navGroup_ClinicalCare: 'क्लिनिकल केअर',
    navGroup_Diagnostics: 'निदान आणि फार्मसी',
    navGroup_PatientFlow: 'रुग्ण प्रवाह आणि बिलिंग',

    mod_home: 'होम',
    mod_dashboard: 'डॅशबोर्ड',
    mod_outpatient: 'बाह्यरुग्ण व्यवस्थापन',
    mod_inpatient: 'आंतररुग्ण व्यवस्थापन',
    mod_nursing: 'नर्सिंग (NIS)',
    mod_clinical_pharm: 'क्लिनिकल फार्मसी',
    mod_tumor_board: 'ट्यूमर बोर्ड',
    mod_quality: 'क्लिनिकल गुणवत्ता',
    mod_lis: 'प्रयोगशाळा माहिती प्रणाली (LIS)',
    mod_ris: 'रेडिओलॉजी माहिती प्रणाली (RIS)',
    mod_pharmacy: 'फार्मसी व्यवस्थापन',
    mod_patient_billing: 'रुग्ण बिलिंग',
    mod_revenue_cycle: 'महसूल चक्र',

    desc_outpatient: 'अॅम्ब्युलेटरी केअर सुलभ करणे',
    desc_inpatient: 'समग्र इनपेशंट केअरचे समन्वय',
    desc_nursing: 'कनेक्टेड नर्सिंग केअर सक्षम करणे',
    desc_clinical_pharm: 'औषध सुरक्षा वाढवा',
    desc_tumor_board: 'सहयोगी कर्करोग उपचार निर्णय',
    desc_quality: 'दर्जेदार आरोग्य सेवा परिणाम',
    desc_lis: 'निदान अचूकता वेगवान करणे',
    desc_ris: 'बुद्धिमान इमेजिंग ऑपरेशन्स',
    desc_pharmacy: 'स्मार्ट औषध व्यवस्थापन',
    desc_patient_billing: 'आर्थिक ऑपरेशन्स सुलभ करणे',
    desc_revenue_cycle: 'महसूल कार्यप्रदर्शन वाढवणे',

    ui_hms: 'रुग्णालय व्यवस्थापन प्रणाली',
    ui_lang: 'भाषा निवडा',
    ui_profile: 'वापरकर्ता प्रोफाइल',
    ui_logout: 'लॉग आउट',
    ui_dept: 'ऑन्कोलॉजी विभाग',
    ui_module_active: 'मॉड्यूल सक्रिय',
    ui_interface_dev: 'इंटरफेस विकास चालू आहे',
    ui_interface_desc: 'हे मॉड्यूल मुख्य विस्टाऑन्को आर्किटेक्चरचा भाग आहे. विशिष्ट वापरकर्ता इंटरफेस घटक सध्या कॉन्फिगर केले जात आहेत.',
    inpatient_admit: 'रुग्ण दाखल करा',
    inpatient_room: 'खोली क्रमांक',
    inpatient_bed: 'बेड क्रमांक',
    inpatient_date: 'दाखल होण्याची तारीख',
    inpatient_status: 'स्थिती',
    inpatient_discharge: 'रुग्णाला डिस्चार्ज द्या',
    inpatient_active: 'सक्रिय दाखल',
    inpatient_history: 'दाखल इतिहास',
    inpatient_no_records: 'कोणतेही सक्रिय दाखल आढळले नाही.',
    inpatient_discharge_date: 'डिस्चार्ज तारीख',
    inpatient_select_patient: 'रुग्ण निवडा',
    btn_cancel: 'रद्द करा',
    btn_save: 'जतन करा',
    nursing_assessment: 'रुग्ण मूल्यांकन',
    nursing_assessment_desc: 'संरचित नर्सिंग मूल्यांकन',
    nursing_med_admin: 'औषध प्रशासन',
    nursing_med_admin_desc: 'सुरक्षित औषध प्रशासन नोंदी',
    nursing_care_plans: 'काळजी योजना',
    nursing_care_plans_desc: 'नर्सिंग काळजी योजना व्यवस्थापन',
    nursing_handover: 'हँडओव्हर नोट्स',
    nursing_handover_desc: 'डिजिटल शिफ्ट हँडओव्हर दस्तऐवजीकरण',
    pharmacy_new_order: 'नवीन ऑर्डर',
    pharmacy_medication: 'औषधाचे नाव',
    pharmacy_dosage: 'डोस',
    pharmacy_frequency: 'वारंवारता',
    pharmacy_active: 'सक्रिय ऑर्डर रांग',
    pharmacy_history: 'वितरित ऑर्डर इतिहास',
    pharmacy_verify: 'ऑर्डर सत्यापित करा',
    pharmacy_dispense: 'वितरित करा',
    pharmacy_status_pending: 'प्रलंबित',
    pharmacy_status_verified: 'सत्यापित',
    pharmacy_status_dispensed: 'वितरित',
    billing_new_invoice: 'नवीन बीजक',
    billing_amount: 'रक्कम (₹)',
    billing_description: 'तपशील',
    billing_unpaid: 'थकीत बीजके',
    billing_paid: 'सशुल्क बीजके इतिहास',
    billing_mark_paid: 'सशुल्क म्हणून चिन्हांकित करा',
    billing_status_unpaid: 'थकीत',
    billing_status_paid: 'सशुल्क',
    billing_total_unpaid: 'एकूण थकीत',
    billing_total_revenue: 'एकूण महसूल',
    tb_meetings: 'बैठका',
    tb_new_meeting: 'बैठक आयोजित करा',
    tb_date: 'बैठकीची तारीख',
    tb_location: 'स्थान',
    tb_cases: 'रुग्णांची प्रकरणे',
    tb_add_case: 'रुग्णाचे प्रकरण सादर करा',
    tb_summary: 'क्लिनिकल सारांश',
    tb_decision: 'बोर्डाचा निर्णय',
    tb_record_decision: 'निर्णय नोंदवा',
    tb_save_decision: 'जतन करा',
    qual_active_incidents: 'सक्रिय घटना',
    qual_resolved_incidents: 'सोडवलेल्या घटनांचा इतिहास',
    qual_report_incident: 'घटनेची तक्रार करा',
    qual_date: 'तारीख',
    qual_department: 'विभाग',
    qual_severity: 'गंभीरता',
    qual_description: 'तपशील',
    qual_status: 'स्थिती',
    qual_resolve: 'सोडवा',
    qual_sev_low: 'कमी',
    qual_sev_medium: 'मध्यम',
    qual_sev_high: 'उच्च',
    qual_sev_critical: 'अत्यंत गंभीर',
    qual_stat_open: 'उघडे',
    qual_stat_investigating: 'चौकशी सुरू',
    qual_stat_resolved: 'सोडवले',
    lis_active_labs: 'सक्रिय लॅब ऑर्डर',
    lis_completed_labs: 'पूर्ण झालेल्या चाचण्या',
    lis_new_order: 'नवीन लॅब ऑर्डर',
    lis_test_name: 'चाचणीचे नाव',
    lis_ordered_by: 'यांच्याद्वारे ऑर्डर केली',
    lis_status: 'स्थिती',
    lis_notes: 'टिपा',
    lis_stat_ordered: 'ऑर्डर केली',
    lis_stat_collected: 'गोळा केली',
    lis_stat_processing: 'प्रक्रिया सुरू',
    lis_stat_resulted: 'निकाल लागला',
    lis_action_collect: 'गोळा केल्याचे चिन्हांकित करा',
    lis_action_process: 'प्रक्रिया सुरू करा',
    lis_action_result: 'निकाल प्रविष्ट करा',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');
  
  const t = (key) => {
    return translations[language][key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
